### ISSUE TITLE
ScopingShim and nested calc issues in IE and Edge <=15

### ISSUE THREAD

**Issue by wessberg** [webcomponents/polyfills#8]
Hi there. Thanks for writing ShadyCSS and for bringing the web forward.

# Problem 
Unfortunately, in IE and Edge <= 15, nested `calc`s (i.e. `calc` inside of another `calc`) are not supported. When using and especially combining CSS custom properties, it is easy to end up combining multiple CSS Custom Properties in `calc` expressions. Some of those may include `calc`s on their own, which leads to this problem.

Developers can get around this by either rewriting their CSS to avoid nested `calc`s, (which can be difficult when using CSS Custom Properties to perform dynamic styling) or use tooling to get around it. For example, in the [postcss](https://github.com/postcss/postcss) ecosystem, combining the [`postcss-custom-properties`](https://github.com/postcss/postcss-custom-properties) and [`postcss-calc`](https://github.com/postcss/postcss-calc) plugins helps reducing and avoiding nested `calc`s to fix styling issues in these browsers.

*However*, not everything can be fixed at compile-time. For example, consider the following:

```css
/* styling applied to 'my-element' */
:host {
    top: calc(var(--foo) - var(--bar));
}

/* somewhere else in some CSS, those properties are set: */
my-element {
    --foo: calc(1px * 2);
    --bar: calc(2px * 2);
}
```

In this example, both `--foo` and `--bar` are dynamic properties, and each of them include a `calc`.

After applying the ScopingShim, the declaration in the CSSOM will be:
```css
top: calc(calc(1px * 2) - calc(2px * 2));
```

Which simply won't work in those browsers.

# Proposed Solution

There's been some effort going into fixing this issue at runtime such as [`css-vars-ponyfill`](https://www.npmjs.com/package/css-vars-ponyfill) that fixes nested `calc`s by default, and I think it would be very valuable for ShadyCSS to do the same thing. I expect some performance overhead since parsing and reducing `calc` rules isn't trivial, but I think it is well worth it.

I've submitted a PR: https://github.com/webcomponents/shadycss/pull/242
